# Generated by Django 6.0.4 on 2026-04-26 20:43

import django.db.models.deletion
import django.utils.timezone
import src.domain.value_objects
import src.infrastructure.orm.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("item_id", models.UUIDField()),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "NEW"),
                            ("PAID", "PAID"),
                            ("SHIPPED", "SHIPPED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "orders",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 1)), name="quantity_ge_1"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("user_id", models.UUIDField()),
                (
                    "amount",
                    src.infrastructure.orm.models.StringDecimalField(
                        decimal_places=2, max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SUCCEEDED", "SUCCEEDED"),
                            ("FAILED", "FAILED"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="src.order",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.CreateModel(
            name="Outbox",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ORDER.CREATED", "CREATED"),
                            ("ORDER.PAID", "PAID"),
                            ("ORDER.SHIPPED", "SHIPPED"),
                            ("ORDER.CANCELLED", "CANCELLED"),
                        ]
                    ),
                ),
                ("payload", models.JSONField(default=None)),
                (
                    "status",
                    models.CharField(
                        choices=src.domain.value_objects.OutboxEventStatusEnum.choices,
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="src.order",
                    ),
                ),
            ],
            options={
                "db_table": "outbox",
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            (
                                "status",
                                src.domain.value_objects.OutboxEventStatusEnum[
                                    "PENDING"
                                ],
                            )
                        ),
                        fields=["status", "created_at"],
                        name="ix_outbox_status_pending",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "event_type"), name="uq_outbox_order_event"
                    )
                ],
            },
        ),
    ]
