# Generated by Django 6.0.4 on 2026-04-27 20:26

import django.utils.timezone
import src.domain.value_objects
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inbox",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("order_id", models.UUIDField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ORDER.SHIPPED", "SHIPPED"),
                            ("ORDER.CANCELLED", "CANCELLED"),
                        ]
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("quantity", models.IntegerField()),
                ("payload", models.JSONField(default=None)),
                (
                    "status",
                    models.CharField(
                        choices=src.domain.value_objects.OutboxEventStatusEnum.choices,
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "inbox",
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            (
                                "status",
                                src.domain.value_objects.InboxEventStatusEnum[
                                    "PENDING"
                                ],
                            )
                        ),
                        fields=["status", "created_at"],
                        name="ix_inbox_status_pending",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order_id", "event_type"), name="uq_inbox_order_event"
                    )
                ],
            },
        ),
    ]
